#! /usr/bin/python

import socket as soc
from urlparse import urlparse
import sys
import os

def downloadrqt(host,path):
	return "GET " + path + " HTTP/1.1\r\n" + "Host: " + host + "\r\n\r\n"

def HEADrqt(host,path):
	return "HEAD " + path + " HTTP/1.1\r\n" + "Host: " + host + "\r\n\r\n"

def conteenew(host,path,byte,contentlength):
	return "GET " + path + " HTTP/1.1\r\n" + "Host: " + host + "\r\n" + "Range: bytes=" +\
	 byte + "-" +contentlength + "\r\n\r\n"
 		
def myreceive(h,file, sock,MSGLEN,name,bytes_recd):
	chunks = []
	while bytes_recd < MSGLEN:
		chunk = sock.recv(min(MSGLEN - bytes_recd, 2048))
		bytes_recd += len(chunk)
		file.write(chunk)
		h.write(str(bytes_recd)+ "\r\n")


def getmeeverything(text,h):
	mydic={}
	i=text.find("\r\n\r\n")
	header = text[:i]
	body=text[i+4:]
	eachhead=header.split("\r\n")

	if not "200" in eachhead[0]:
		print "Sorry! We caught an error!"
		sys.exit(2)

	for each in eachhead[1:]:
		hm=each.split(": ")
		if "Content-Length" in each or "Last-Modified" in each or "ETag" in each:
			h.write(each+"\r\n")
		mydic[hm[0]]= hm[1]
	return mydic,body

def getmeeverythingforresume(text):
	mydic={}
	i=text.find("\r\n\r\n")
	header = text[:i]
	body=text[i+4:]
	eachhead=header.split("\r\n")

	if not "200" in eachhead[0]:
		print "Sorry! We caught an error!"
		sys.exit(2)

	for each in eachhead[1:]:
		hm=each.split(": ")
		mydic[hm[0]]= hm[1]
	return mydic,body

def downloadpls(HOST,PORT,PATH,name):
	fname,extension= name.split(".")
	with open(fname+ "sanchit","wb+") as file:
		with open("meta.txt","wb+") as h:
			clientSocket = soc.socket(soc.AF_INET, soc.SOCK_STREAM)
			clientSocket.connect((HOST,PORT))
			header = downloadrqt(HOST,PATH)
			clientSocket.send(header)
			text = "" 
			while True:
				res = clientSocket.recv(1024)	
				text += res
				if "\r\n\r\n" in text:
					mydic ,body= getmeeverything(text,h)
					file.write(body)
					h.write(str(len(text))+ "\r\n")
					length= int(mydic["Content-Length"])
					myreceive(h,file, clientSocket, long(length), name, long(len(body)))
					clientSocket.close()
					break	
			os.rename(fname+"sanchit", fname + "." + extension)
			os.remove("meta.txt")
	

def resumedownload(HOST,PORT,PATH,name):
	fname,extension= name.split(".")
	clientSocket = soc.socket(soc.AF_INET, soc.SOCK_STREAM)
	clientSocket.connect((HOST,PORT))
	header = HEADrqt(HOST,PATH)	
	clientSocket.send(header)
	text=""
	oldFile = fname+"sanchit"
	while True:
		res = clientSocket.recv(1024)	
		text += res
		if "\r\n\r\n" in text:
			mydic ,body= getmeeverythingforresume(text)
			try:
				Etag= mydic["ETag"]
				Last= mydic["Last-Modified"]
			except Exception as e:
				print "Server Doesn't support resuming"
				sys.exit()
			length= int(mydic["Content-Length"])
			clientSocket.close()
			break

	if os.path.isfile(oldFile):
		lst = []
        string = oldFile
        lst = string.split("\r\n")
        with open("meta.txt","r") as fffile:
			byte = fffile.readlines()
			hm,prevEtag= byte[1].split(": ")
			hmmmm,prevLast= byte[0].split(": ")
			hmmm,prevLength = byte[2].split(": ")
			sizz= byte[-1].strip()
	
	clientSocket = soc.socket(soc.AF_INET, soc.SOCK_STREAM)
	clientSocket.connect((HOST,PORT))
	header = conteenew(HOST,PATH,sizz,str(length))
	clientSocket.send(header)
	print header
	writeout= open(name,"a+")

	if prevLast.strip()== Last and Etag.strip()==prevEtag:
		try:
			while True:
				tempname = fname +"sanchit" 	
				print "hey"
				res = clientSocket.recv(1024)
				print "hey2"
				text+= res
				lenn=len(text)
				writeout.write(text)
				if lenn + int(sizz) < length :
					with open(writeout,"r") as newman:
						f_old = open(oldaf,"a+")
						for line in newman:
							f_old.write(line)
						f_old.close()
					#directory = os.getcwd()
					os.remove(tempname)
					os.remove("meta.txt")
					print "hey3"
					break
		except KeyboardInterrupt  as e:
			print "Oh man I hate your keyboard"
	else:
		downloadpls(HOST,PORT,PATH,name)

	writeout.close()

def append_file(original,new):
    f_old = open(original,"a+")
    f_new = open(new,"r")
    for line in f_new:
        f_old.write(line)
    f_old.close()
    f_new.close()
    os.remove(new) 


if len(sys.argv) ==4 and sys.argv[1]== "-o":
	if "https" in sys.argv[-1]:
		print "Sorry we don't support https"	
		sys.exit(2)
	parseSTR = urlparse(sys.argv[-1])
	if parseSTR.port == None: PORT = 80
	else: PORT = parseSTR.port
	fileName=sys.argv[2]
	fname,extension= fileName.split(".")
	HOST = parseSTR.hostname
	PATH = parseSTR.path
	if PATH=="" or PATH== None:
		PATH="/"
	if os.path.isfile(fname+"sanchit"):
		resumedownload(HOST,PORT,PATH,fileName)
	else:
		downloadpls(HOST,PORT,PATH,fileName)
	
